#!/usr/bin/env python3
"""Build a portable double-clickable macOS .app for M Maps.

Produces ``dist/M Maps.app`` that is self-contained for distribution:

- App code (``mmaps/``) → ``Contents/Resources/app/``
- Pip dependencies → ``Contents/Resources/vendor/``
- A copy of the CLT **Python3.framework** → ``Contents/Frameworks/``
- An in-bundle interpreter binary ``Contents/MacOS/python-run`` (rpath fixed)
- Launcher ``Contents/MacOS/M Maps`` exec's that **in-bundle** interpreter

Why embed the interpreter (not system ``python3``)?

  If the process image after launch is system Python
  (…/Python.app/Contents/MacOS/Python), Launch Services / Dock / Cmd+Tab
  identify the process as "Python" — no amount of in-process CFBundleName
  patching changes ``NSRunningApplication.localizedName`` for that case.

  When the interpreter binary lives *inside* M Maps.app and is not nested
  under a second .app (we strip the framework's Resources/Python.app),
  ``NSBundle.mainBundle`` and Launch Services resolve to **M Maps.app**, so
  Dock tooltips and the app switcher show "M Maps".

Nothing is hardcoded to a developer checkout path. The launcher is checked
for forbidden path substrings at build time.
"""
from __future__ import annotations

import os
import plistlib
import shutil
import stat
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
DIST = PROJECT_ROOT / "dist"
APP_NAME = "M Maps"
BUNDLE_ID = "local.mmaps.app"
ICON_ICNS = PROJECT_ROOT / "assets" / "icon" / "AppIcon.icns"
ICON_BASE_NAME = "AppIcon"
REQUIREMENTS = PROJECT_ROOT / "requirements.txt"
MMAPS_PKG = PROJECT_ROOT / "mmaps"

CLT_FRAMEWORK = Path(
    "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework"
)
# Real interpreter binary (not the bin/ stub that re-execs into Python.app).
CLT_PYTHON_APP_BIN = (
    CLT_FRAMEWORK
    / "Versions"
    / "3.9"
    / "Resources"
    / "Python.app"
    / "Contents"
    / "MacOS"
    / "Python"
)
# Fallback discovery if CLT layout differs slightly.
SYSTEM_PYTHON = Path("/usr/bin/python3")


def _launcher_script() -> str:
    # Paths resolved at runtime from $0 — never baked to a build machine path.
    # Exec's the *in-bundle* python-run so LS identity stays M Maps.app.
    return r"""#!/bin/bash
# Auto-generated by build_app.py — do not edit by hand.
set -e
export PATH="/usr/bin:/bin:/usr/sbin:/sbin"

MACOS_DIR="$(cd "$(dirname "$0")" && pwd)"
CONTENTS_DIR="$(cd "$MACOS_DIR/.." && pwd)"
RES="$CONTENTS_DIR/Resources"
APP_DIR="$RES/app"
VENDOR_DIR="$RES/vendor"
FW_HOME="$CONTENTS_DIR/Frameworks/Python3.framework/Versions/3.9"
PY_RUN="$MACOS_DIR/python-run"

if [ ! -d "$APP_DIR/mmaps" ]; then
  echo "M Maps is damaged or incomplete (missing Resources/app/mmaps)." >&2
  exit 1
fi
if [ ! -d "$VENDOR_DIR" ]; then
  echo "M Maps is damaged or incomplete (missing Resources/vendor)." >&2
  exit 1
fi
if [ ! -x "$PY_RUN" ]; then
  echo "M Maps is damaged or incomplete (missing MacOS/python-run)." >&2
  exit 1
fi
if [ ! -d "$FW_HOME" ]; then
  echo "M Maps is damaged or incomplete (missing embedded Python3.framework)." >&2
  exit 1
fi

export PYTHONPATH="$APP_DIR:$VENDOR_DIR${PYTHONPATH:+:$PYTHONPATH}"
export PYTHONHOME="$FW_HOME"
export MMAPS_APP_BUNDLE="$(cd "$CONTENTS_DIR/.." && pwd)"
export MMAPS_APP_NAME="M Maps"

# Stay inside the bundle after exec so Dock / Cmd+Tab resolve to this .app.
cd "$APP_DIR"
exec -a "M Maps" "$PY_RUN" -m mmaps.desktop "$@"
"""


def _info_plist() -> dict:
    try:
        from mmaps import __version__ as app_version
    except Exception:
        app_version = "1.0.0"
    return {
        "CFBundleDevelopmentRegion": "en",
        "CFBundleDisplayName": APP_NAME,
        "CFBundleExecutable": APP_NAME,
        "CFBundleIconFile": ICON_BASE_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundleName": APP_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": str(app_version),
        "CFBundleVersion": str(app_version),
        "LSMinimumSystemVersion": "12.0",
        "NSHighResolutionCapable": True,
        "NSPrincipalClass": "NSApplication",
        "NSAppTransportSecurity": {
            "NSAllowsArbitraryLoadsInWebContent": True,
            "NSAllowsLocalNetworking": True,
        },
    }


def _copy_app_package(dest_app: Path) -> None:
    dest_pkg = dest_app / "mmaps"
    if dest_pkg.exists():
        shutil.rmtree(dest_pkg)
    shutil.copytree(
        MMAPS_PKG,
        dest_pkg,
        ignore=shutil.ignore_patterns("__pycache__", "*.py[cod]", ".DS_Store"),
    )


def _install_vendor(vendor_dir: Path) -> None:
    if vendor_dir.exists():
        shutil.rmtree(vendor_dir)
    vendor_dir.mkdir(parents=True, exist_ok=True)
    pip = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--disable-pip-version-check",
        "--no-compile",
        "-r",
        str(REQUIREMENTS),
        "-t",
        str(vendor_dir),
    ]
    print("Installing dependencies into bundle (this may take a minute)…")
    subprocess.check_call(pip)
    scripts = vendor_dir / "bin"
    if scripts.is_dir():
        shutil.rmtree(scripts)
    for junk in vendor_dir.glob("**/*.pyc"):
        try:
            junk.unlink()
        except OSError:
            pass


def _embed_python(contents: Path) -> Path:
    """Copy CLT Python3.framework + a MacOS/python-run binary with fixed rpath.

    Returns path to python-run.
    """
    if not CLT_FRAMEWORK.is_dir():
        raise SystemExit(
            f"Missing {CLT_FRAMEWORK}.\n"
            "Install Xcode Command Line Tools (xcode-select --install)."
        )
    if not CLT_PYTHON_APP_BIN.is_file():
        raise SystemExit(
            f"Missing interpreter binary {CLT_PYTHON_APP_BIN}.\n"
            "Unexpected CLT Python layout — please report this."
        )

    frameworks = contents / "Frameworks"
    frameworks.mkdir(parents=True, exist_ok=True)
    dest_fw = frameworks / "Python3.framework"
    if dest_fw.exists():
        shutil.rmtree(dest_fw)
    print("Embedding Python3.framework into the app bundle…")
    shutil.copytree(
        CLT_FRAMEWORK,
        dest_fw,
        symlinks=True,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )
    # Nested Python.app makes mainBundle resolve to "Python" instead of M Maps.
    nested = dest_fw / "Versions" / "3.9" / "Resources" / "Python.app"
    if nested.exists():
        shutil.rmtree(nested)

    macos = contents / "MacOS"
    python_run = macos / "python-run"
    shutil.copy2(CLT_PYTHON_APP_BIN, python_run)
    python_run.chmod(python_run.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # Original load: @executable_path/../../../../Python3 (from nested Python.app).
    # From Contents/MacOS/python-run we need Frameworks/.../Python3.
    new_load = "@executable_path/../Frameworks/Python3.framework/Versions/3.9/Python3"
    old_load = "@executable_path/../../../../Python3"
    try:
        subprocess.check_call(
            ["install_name_tool", "-change", old_load, new_load, str(python_run)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except subprocess.CalledProcessError as exc:
        raise SystemExit(
            f"install_name_tool failed while fixing python-run rpath: {exc}"
        ) from exc

    # Ad-hoc sign after rewriting load commands (required on modern macOS).
    try:
        subprocess.check_call(
            ["codesign", "-s", "-", "-f", str(python_run)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        # Still often runnable without re-sign on some systems; continue.
        pass

    return python_run


def _assert_no_dev_paths(app_dir: Path) -> None:
    launcher = app_dir / "Contents" / "MacOS" / APP_NAME
    text = launcher.read_text(encoding="utf-8")
    for needle in ("/Users/", "/home/", "Developer/m-maps", "venv/bin"):
        if needle in text:
            raise SystemExit(
                f"Portability check failed: launcher contains {needle!r}.\n"
                f"  {launcher}"
            )
    # Must not exec system python paths either.
    for needle in (
        "/Library/Developer/CommandLineTools/usr/bin/python",
        "/usr/bin/python",
    ):
        if needle in text:
            raise SystemExit(
                f"Portability/identity check failed: launcher references system "
                f"Python path {needle!r} — Dock would show as Python.\n"
                f"  {launcher}"
            )


def build() -> Path:
    if sys.platform != "darwin":
        raise SystemExit("Building the .app is macOS-only.")
    if not MMAPS_PKG.is_dir():
        raise SystemExit(f"Missing package: {MMAPS_PKG}")
    if not REQUIREMENTS.is_file():
        raise SystemExit(f"Missing {REQUIREMENTS}")
    if not ICON_ICNS.is_file():
        raise SystemExit(
            f"Missing app icon {ICON_ICNS}.\n"
            "Run: venv/bin/python3 scripts/make_app_icon.py"
        )

    app_dir = DIST / f"{APP_NAME}.app"
    contents = app_dir / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"
    app_code = resources / "app"
    vendor = resources / "vendor"

    if app_dir.exists():
        shutil.rmtree(app_dir)
    macos.mkdir(parents=True, exist_ok=True)
    resources.mkdir(parents=True, exist_ok=True)

    executable = macos / APP_NAME
    executable.write_text(_launcher_script(), encoding="utf-8")
    executable.chmod(
        executable.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
    )

    with (contents / "Info.plist").open("wb") as fh:
        plistlib.dump(_info_plist(), fh)
    (contents / "PkgInfo").write_text("APPL????", encoding="ascii")
    shutil.copy2(ICON_ICNS, resources / f"{ICON_BASE_NAME}.icns")

    print("Copying mmaps package into Resources/app …")
    _copy_app_package(app_code)
    _install_vendor(vendor)
    python_run = _embed_python(contents)
    _assert_no_dev_paths(app_dir)

    # Smoke: in-bundle interpreter imports app + vendor + reports mainBundle name.
    env = os.environ.copy()
    env["PYTHONPATH"] = f"{app_code}{os.pathsep}{vendor}"
    env["PYTHONHOME"] = str(
        contents / "Frameworks" / "Python3.framework" / "Versions" / "3.9"
    )
    env["MMAPS_APP_BUNDLE"] = str(app_dir)
    env["MMAPS_APP_NAME"] = APP_NAME
    subprocess.check_call(
        [
            str(python_run),
            "-c",
            "import mmaps.desktop, mmaps.server, webview, pymobiledevice3;"
            "from Foundation import NSBundle;"
            f"b=NSBundle.mainBundle();"
            f"assert b and 'M Maps.app' in str(b.bundlePath()), b.bundlePath();"
            f"assert (b.infoDictionary() or {{}}).get('CFBundleName')=='M Maps';"
            "print('in-bundle identity smoke OK', b.bundlePath())",
        ],
        env=env,
        cwd=str(app_code),
    )

    size_mb = sum(
        p.stat().st_size for p in app_dir.rglob("*") if p.is_file()
    ) / (1024 * 1024)
    print(f"Built: {app_dir}  (~{size_mb:.0f} MB)")
    print(f"Icon:  {resources / (ICON_BASE_NAME + '.icns')}")
    print("Interpreter: Contents/MacOS/python-run (inside .app — Dock identity)")
    print(f"Double-click it, or: open {app_dir!s}")
    return app_dir


if __name__ == "__main__":
    build()
