#!/usr/bin/env python3
"""Build a portable double-clickable macOS .app for M Maps via **PyInstaller**.

Produces ``dist/M Maps.app`` that is self-contained for distribution.

Why PyInstaller (not an embedded Python.framework + shell launcher):

  Handing execution to a separate Python binary (system Python, or a
  framework copy that still behaves like one) lets Launch Services /
  WindowServer re-register the process under Python's identity. The Dock
  and Cmd+Tab then intermittently show Python's icon during launch.

  PyInstaller's bootloader lives at ``Contents/MacOS/M Maps`` and loads
  the interpreter **in-process** via ``dlopen()``. There is no nested
  Python.app process identity for the OS to confuse with M Maps.
  ``[NSBundle mainBundle]`` resolves to M Maps.app for the whole lifetime.

What is preserved from the previous packaging work:

- No hardcoded personal / checkout paths (build fails if ``/Users/`` etc.
  appear in launcher-facing text or the main executable's strings).
- All app code + pip deps ship inside the bundle (no venv / repo needed
  at runtime).
- ``assets/icon/AppIcon.icns`` is the bundle icon.
- Desktop elevation (``osascript`` admin dialog → root tunnel server)
  still works via the console ``mmaps-server`` helper (not the windowed GUI).

Usage:
    venv/bin/python3 build_app.py
"""
from __future__ import annotations

import os
import plistlib
import shutil
import stat
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
DIST = PROJECT_ROOT / "dist"
BUILD_DIR = PROJECT_ROOT / "build" / "pyinstaller"
SPEC_PATH = PROJECT_ROOT / "packaging" / "m_maps.spec"
ENTRY = PROJECT_ROOT / "packaging" / "desktop_entry.py"
APP_NAME = "M Maps"
BUNDLE_ID = "local.mmaps.app"
ICON_ICNS = PROJECT_ROOT / "assets" / "icon" / "AppIcon.icns"
ICON_BASE_NAME = "AppIcon"
REQUIREMENTS = PROJECT_ROOT / "requirements.txt"
MMAPS_PKG = PROJECT_ROOT / "mmaps"

def _forbidden_path_needles() -> tuple[str, ...]:
    """Paths that prove the bundle is tied to this build machine.

    We do **not** ban the bare substrings ``/Users/`` or ``/home/`` — third-party
    libraries and pip ``.dist-info/RECORD`` files often mention them without the
    app ever opening those paths. We ban *this* checkout and *this* home.
    """
    needles = [
        str(PROJECT_ROOT),
        "Developer/m-maps",
        "venv/bin",
        str(Path.home()),  # e.g. /Users/mj
    ]
    # Dedupe while preserving order.
    seen = set()
    out: list[str] = []
    for n in needles:
        if n and n not in seen:
            seen.add(n)
            out.append(n)
    return tuple(out)


def _app_version() -> str:
    try:
        from mmaps import __version__ as app_version

        return str(app_version)
    except Exception:
        return "1.0.0"


def _ensure_entry_and_spec() -> None:
    """Write packaging entry + .spec (always regenerated so version stays fresh)."""
    packaging = PROJECT_ROOT / "packaging"
    packaging.mkdir(parents=True, exist_ok=True)

    ENTRY.write_text(
        '''#!/usr/bin/env python3
"""PyInstaller entry point for the M Maps desktop app.

Kept separate from mmaps.desktop so Analysis has a stable script path and
the frozen bootloader can re-exec itself with --server-only for elevation.
"""
from __future__ import annotations

from mmaps.desktop import main

if __name__ == "__main__":
    raise SystemExit(main())
''',
        encoding="utf-8",
    )
    SPEC_PATH.write_text(_render_spec(_app_version()), encoding="utf-8")


def _render_spec(version: str) -> str:
    root = str(PROJECT_ROOT)
    icon = str(ICON_ICNS)
    # Use a plain template with replacements to avoid brace escaping bugs.
    return f'''# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_app.py — do not edit by hand.
# PyInstaller onedir + windowed → dist/M Maps.app with in-process bootloader.

block_cipher = None

from pathlib import Path
from PyInstaller.utils.hooks import collect_all, collect_submodules

_ROOT = Path(r"{root}")
_ICON = r"{icon}"

_datas = [
    (str(_ROOT / "mmaps" / "web"), "mmaps/web"),
    (str(_ROOT / "mmaps" / "data"), "mmaps/data"),
]
_binaries = []
_hidden = [
    "mmaps",
    "mmaps.desktop",
    "mmaps.server",
    "mmaps.session",
    "mmaps.device",
    "mmaps.location",
    "mmaps.route",
    "mmaps.flight",
    "mmaps.airports",
    "mmaps.trip",
    "mmaps.errors",
    "mmaps.cli",
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "webview",
    "webview.platforms.cocoa",
]

for _pkg in ("pymobiledevice3", "webview", "fastapi", "starlette", "anyio"):
    try:
        d, b, h = collect_all(_pkg)
        _datas += d
        _binaries += b
        _hidden += h
    except Exception:
        pass

try:
    _hidden += collect_submodules("uvicorn")
except Exception:
    pass

a = Analysis(
    [str(_ROOT / "packaging" / "desktop_entry.py")],
    pathex=[str(_ROOT)],
    binaries=_binaries,
    datas=_datas,
    hiddenimports=list(dict.fromkeys(_hidden)),
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[str(_ROOT / "packaging" / "rthook_stub_ipython.py")],
    # IPython is only used by pymobiledevice3 for an optional CLI shell; the
    # real stack breaks in a windowed frozen app. Stubbed via runtime hook.
    excludes=[
        "IPython",
        "jedi",
        "prompt_toolkit",
        "matplotlib",
        "notebook",
        "jupyter",
        "jupyter_client",
        "jupyter_core",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# GUI bootloader (windowed runw) — Dock / Cmd+Tab identity for the user process.
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="M Maps",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=True,
    target_arch=None,
    codesign_identity="-",
    entitlements_file=None,
    icon=_ICON,
)

# Headless elevated tunnel/server helper (console run bootloader).
# Must NOT re-use the windowed "M Maps" binary: a second runw instance of the
# same .app fights the GUI process (Dock/AppKit contention → beachball / ANR).
exe_server = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="mmaps-server",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity="-",
    entitlements_file=None,
)

# Order matters: BUNDLE takes console= from the last EXE. Keep the GUI
# (console=False) last so PyInstaller does not mark the whole .app as a
# background-only agent (that was making the Dock icon ignore system tint).
coll = COLLECT(
    exe_server,
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="M Maps",
)

app = BUNDLE(
    coll,
    name="M Maps.app",
    icon=_ICON,
    bundle_identifier="{BUNDLE_ID}",
    version="{version}",
    info_plist={{
        "CFBundleDevelopmentRegion": "en",
        "CFBundleDisplayName": "M Maps",
        "CFBundleExecutable": "M Maps",
        "CFBundleIconFile": "AppIcon",
        # Lets Launch Services resolve the named icon asset (matches Safari/etc.).
        "CFBundleIconName": "AppIcon",
        "CFBundleIdentifier": "{BUNDLE_ID}",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundleName": "M Maps",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": "{version}",
        "CFBundleVersion": "{version}",
        "LSMinimumSystemVersion": "12.0",
        # CRITICAL: console helper must not force background-only on the GUI app.
        # LSBackgroundOnly=true → Dock skips normal app-icon styling/tint.
        "LSBackgroundOnly": False,
        "LSUIElement": False,
        "NSHighResolutionCapable": True,
        "NSPrincipalClass": "NSApplication",
        "NSAppTransportSecurity": {{
            "NSAllowsArbitraryLoadsInWebContent": True,
            "NSAllowsLocalNetworking": True,
        }},
    }},
)
'''


def _strip_packaging_metadata(app_dir: Path) -> None:
    """Remove pip dist-info / egg-info (install records, not needed at runtime)."""
    for pattern in ("**/*.dist-info", "**/*.egg-info"):
        for path in app_dir.glob(pattern):
            # PyInstaller's macOS bundle contains each metadata directory in
            # Resources plus a companion symlink in Frameworks. Removing only
            # the directory leaves a broken symlink, which makes deep codesign
            # verification fail even though the application can still launch.
            if path.is_symlink():
                path.unlink(missing_ok=True)
            elif path.is_dir():
                shutil.rmtree(path, ignore_errors=True)
            elif path.exists():
                path.unlink()


def _assert_no_dev_paths(app_dir: Path) -> None:
    """Fail the build if *this machine's* checkout/home leaked into critical files.

    Real portability is proven by the rename-away smoke test. This scan catches
    accidental hardcoding in Info.plist, the bootloader, and our own resources.
    Third-party library source that mentions generic Unix paths is ignored.
    """
    needles = _forbidden_path_needles()
    offenders: list[str] = []

    critical_globs = [
        "Contents/Info.plist",
        "Contents/PkgInfo",
        "Contents/MacOS/*",
        "Contents/Resources/mmaps/**",
    ]
    critical_files: list[Path] = []
    for g in critical_globs:
        critical_files.extend(app_dir.glob(g))

    text_suffixes = {
        "",
        ".plist",
        ".txt",
        ".json",
        ".cfg",
        ".conf",
        ".sh",
        ".py",
        ".html",
        ".js",
        ".css",
        ".xml",
        ".strings",
    }
    for path in critical_files:
        if not path.is_file():
            continue
        if path.stat().st_size > 2_000_000:
            continue
        suffix = path.suffix.lower()
        # Always scan the bootloader via strings; skip binary read as text.
        if path.parent.name == "MacOS" and suffix == "":
            continue
        if suffix not in text_suffixes and path.name not in ("PkgInfo", "Info.plist"):
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for needle in needles:
            if needle in text:
                offenders.append(f"{path.relative_to(app_dir)}: contains {needle!r}")
                break

    macos_exe = app_dir / "Contents" / "MacOS" / APP_NAME
    if macos_exe.is_file():
        try:
            out = subprocess.check_output(
                ["strings", "-a", str(macos_exe)],
                stderr=subprocess.DEVNULL,
            )
            blob = out.decode("latin-1", errors="ignore")
            for needle in needles:
                if needle in blob:
                    # Bootloader itself must not embed the checkout path as a
                    # runtime string. (PYZ .pyc co_filenames live elsewhere.)
                    offenders.append(
                        f"{macos_exe.relative_to(app_dir)}: strings contain {needle!r}"
                    )
                    break
        except (FileNotFoundError, subprocess.CalledProcessError, OSError):
            pass

    if offenders:
        detail = "\n  ".join(offenders[:20])
        raise SystemExit(
            "Portability check failed — bundle contains developer paths:\n"
            f"  {detail}\n"
            "The app must not hardcode this machine's home or checkout path."
        )


def _resign_app_bundle(app_dir: Path) -> None:
    """Ad-hoc sign the whole .app so bootloader + Python.framework share one identity.

    PyInstaller ad-hoc-signs the bootloader, but the copied CLT Python3.framework
    still carries Apple's signature. macOS then refuses dlopen with
    "different Team IDs". Deep ad-hoc re-sign unifies the bundle.
    """
    print("Ad-hoc codesign (deep) so bootloader can dlopen embedded Python…")
    # Prefer deep sign of the bundle; fall back to Frameworks then MacOS then .app.
    try:
        subprocess.check_call(
            [
                "codesign",
                "--force",
                "--deep",
                "--sign",
                "-",
                str(app_dir),
            ],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
        )
        return
    except subprocess.CalledProcessError as first:
        err1 = (first.stderr or b"").decode("utf-8", errors="replace")
    # Manual inside-out sign.
    targets: list[Path] = []
    frameworks = app_dir / "Contents" / "Frameworks"
    if frameworks.is_dir():
        for p in sorted(frameworks.rglob("*"), key=lambda x: len(x.parts), reverse=True):
            if not p.is_file():
                continue
            if p.suffix in (".dylib", ".so") or p.name in (
                "Python3",
                "Python",
                APP_NAME,
            ):
                targets.append(p)
        # Framework binary
        py = frameworks / "Python3.framework" / "Versions" / "3.9" / "Python3"
        if py.is_file():
            targets.append(py)
    macos_exe = app_dir / "Contents" / "MacOS" / APP_NAME
    if macos_exe.is_file():
        targets.append(macos_exe)
    # Elevated helper must share the ad-hoc identity or dlopen fails under root.
    helper = app_dir / "Contents" / "MacOS" / "mmaps-server"
    if helper.is_file():
        targets.append(helper)
    targets.append(app_dir)
    last_err = err1
    for t in targets:
        try:
            subprocess.check_call(
                ["codesign", "--force", "--sign", "-", str(t)],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
            )
        except subprocess.CalledProcessError as exc:
            last_err = (exc.stderr or b"").decode("utf-8", errors="replace")
    # Final deep
    try:
        subprocess.check_call(
            ["codesign", "--force", "--deep", "--sign", "-", str(app_dir)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
        )
    except subprocess.CalledProcessError as exc:
        last_err = (exc.stderr or b"").decode("utf-8", errors="replace")
        raise SystemExit(
            "codesign failed — the app cannot load its embedded Python.\n"
            f"{last_err}"
        ) from exc


def _assert_icon_present(app_dir: Path) -> None:
    resources = app_dir / "Contents" / "Resources"
    candidates = list(resources.glob("*.icns")) if resources.is_dir() else []
    # PyInstaller may name the icon after the app or keep AppIcon.
    if not candidates:
        raise SystemExit(f"No .icns found under {resources}")
    # Prefer AppIcon.icns; if PyInstaller used another name, copy/link for desktop.py
    app_icon = resources / f"{ICON_BASE_NAME}.icns"
    if not app_icon.is_file():
        # Copy first icns to the name desktop.py and Info.plist expect.
        shutil.copy2(candidates[0], app_icon)
    if app_icon.stat().st_size < 1000:
        raise SystemExit(f"Icon looks empty: {app_icon}")


def _assert_gui_info_plist(app_dir: Path) -> None:
    """Ensure the .app is a normal Dock GUI app (not a background agent)."""
    plist_path = app_dir / "Contents" / "Info.plist"
    with plist_path.open("rb") as fh:
        info = plistlib.load(fh)
    # Force-correct if PyInstaller still stamped background-only.
    dirty = False
    if info.get("LSBackgroundOnly"):
        info["LSBackgroundOnly"] = False
        dirty = True
    if info.get("LSUIElement"):
        info["LSUIElement"] = False
        dirty = True
    if info.get("CFBundleIconFile") not in ("AppIcon", "AppIcon.icns"):
        info["CFBundleIconFile"] = "AppIcon"
        dirty = True
    if info.get("CFBundleIconName") != "AppIcon":
        info["CFBundleIconName"] = "AppIcon"
        dirty = True
    if dirty:
        with plist_path.open("wb") as fh:
            plistlib.dump(info, fh)
        print("Corrected Info.plist for Dock GUI + icon tint (LSBackgroundOnly=false).")
    if info.get("LSBackgroundOnly"):
        raise SystemExit("Info.plist still has LSBackgroundOnly — Dock tint will break.")


def _assert_server_helper(app_dir: Path) -> None:
    """Elevated tunnel must use the console helper, not the windowed bootloader."""
    helper = app_dir / "Contents" / "MacOS" / "mmaps-server"
    gui = app_dir / "Contents" / "MacOS" / APP_NAME
    if not helper.is_file():
        raise SystemExit(
            f"Missing headless server helper: {helper}\n"
            "The elevated process must not re-exec the windowed GUI bootloader."
        )
    if not gui.is_file():
        raise SystemExit(f"Missing GUI bootloader: {gui}")
    helper.chmod(helper.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    # Helpers should be distinct binaries (console vs windowed bootloaders).
    if helper.resolve() == gui.resolve():
        raise SystemExit("mmaps-server must not be the same file as the GUI bootloader")


def _run_pyinstaller() -> Path:
    pyinstaller = Path(sys.executable).parent / "pyinstaller"
    if not pyinstaller.is_file():
        # Module form works even if console script name differs.
        cmd = [
            sys.executable,
            "-m",
            "PyInstaller",
            "--noconfirm",
            "--clean",
            "--distpath",
            str(DIST),
            "--workpath",
            str(BUILD_DIR),
            str(SPEC_PATH),
        ]
    else:
        cmd = [
            str(pyinstaller),
            "--noconfirm",
            "--clean",
            "--distpath",
            str(DIST),
            "--workpath",
            str(BUILD_DIR),
            str(SPEC_PATH),
        ]
    print("Running PyInstaller (windowed onedir → .app)…")
    print(" ", " ".join(cmd))
    subprocess.check_call(cmd, cwd=str(PROJECT_ROOT))
    app_dir = DIST / f"{APP_NAME}.app"
    if not app_dir.is_dir():
        raise SystemExit(f"PyInstaller did not produce {app_dir}")
    return app_dir


def _smoke_identity_and_imports(app_dir: Path) -> None:
    """Run the bootloader with --bundle-smoke (no GUI, no root)."""
    app_dir = app_dir.resolve()
    exe = app_dir / "Contents" / "MacOS" / APP_NAME
    if not exe.is_file():
        raise SystemExit(f"Missing bootloader executable: {exe}")
    # Ensure executable bit.
    exe.chmod(exe.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    env = os.environ.copy()
    # Do not inherit a PYTHONPATH that points at the checkout — the frozen
    # app must resolve modules from inside the bundle only.
    env.pop("PYTHONPATH", None)
    env.pop("PYTHONHOME", None)

    print("Smoke: frozen bootloader --bundle-smoke …")
    proc = subprocess.run(
        [str(exe), "--bundle-smoke"],
        env=env,
        cwd="/tmp",
        capture_output=True,
        text=True,
        timeout=120,
    )
    out = (proc.stdout or "") + (proc.stderr or "")
    print(out.strip() or "(no smoke output)")
    if proc.returncode != 0:
        raise SystemExit(
            f"Bundle smoke failed (exit {proc.returncode}).\n{out}"
        )
    if "M Maps.app" not in out and "bundle_ok" not in out:
        raise SystemExit(
            "Bundle smoke did not confirm M Maps.app mainBundle identity.\n"
            f"Output:\n{out}"
        )


def _smoke_portability_rename(app_dir: Path) -> None:
    """Copy app elsewhere; run smoke with the project mmaps/ renamed away."""
    import tempfile

    print("Smoke: portability (copy app + hide checkout package) …")
    with tempfile.TemporaryDirectory(prefix="mmaps-portable-") as tmp:
        tmp_path = Path(tmp)
        portable = tmp_path / f"{APP_NAME}.app"
        shutil.copytree(app_dir, portable, symlinks=True)
        exe = portable / "Contents" / "MacOS" / APP_NAME

        # Hide the source package so an accidental PYTHONPATH / cwd import fails.
        hidden = None
        mmaps_src = MMAPS_PKG
        if mmaps_src.is_dir():
            hidden = mmaps_src.with_name("mmaps.__hidden_for_portable_test__")
            if hidden.exists():
                shutil.rmtree(hidden)
            mmaps_src.rename(hidden)
        try:
            env = os.environ.copy()
            env.pop("PYTHONPATH", None)
            env.pop("PYTHONHOME", None)
            proc = subprocess.run(
                [str(exe), "--bundle-smoke"],
                env=env,
                cwd=str(tmp_path),
                capture_output=True,
                text=True,
                timeout=120,
            )
            out = (proc.stdout or "") + (proc.stderr or "")
            print(out.strip() or "(no portable smoke output)")
            if proc.returncode != 0:
                raise SystemExit(
                    f"Portable smoke failed (exit {proc.returncode}).\n{out}"
                )
            if "bundle_ok" not in out and "M Maps.app" not in out:
                raise SystemExit(
                    f"Portable smoke did not confirm identity.\n{out}"
                )
            print("Portability smoke OK (checkout mmaps/ was renamed away).")
        finally:
            if hidden is not None and hidden.exists() and not mmaps_src.exists():
                hidden.rename(mmaps_src)


def build() -> Path:
    if sys.platform != "darwin":
        raise SystemExit("Building the .app is macOS-only.")
    if not MMAPS_PKG.is_dir():
        raise SystemExit(f"Missing package: {MMAPS_PKG}")
    if not REQUIREMENTS.is_file():
        raise SystemExit(f"Missing {REQUIREMENTS}")
    if not ICON_ICNS.is_file():
        raise SystemExit(
            f"Missing app icon {ICON_ICNS}.\n"
            "Run: venv/bin/python3 scripts/make_app_icon.py"
        )

    # Ensure PyInstaller is available in this interpreter.
    try:
        import PyInstaller  # noqa: F401
    except ImportError as exc:
        raise SystemExit(
            "PyInstaller is not installed in this Python.\n"
            f"  {sys.executable} -m pip install 'pyinstaller>=6.0'\n"
            f"({exc})"
        ) from exc

    _ensure_entry_and_spec()

    # Remove previous app so we never mix toolchains.
    app_dir = DIST / f"{APP_NAME}.app"
    if app_dir.exists():
        shutil.rmtree(app_dir)
    # Also remove onedir COLLECT folder if PyInstaller left one beside the .app
    coll_dir = DIST / APP_NAME
    if coll_dir.is_dir() and not str(coll_dir).endswith(".app"):
        shutil.rmtree(coll_dir)

    app_dir = _run_pyinstaller()
    # COLLECT leaves a bare onedir next to the .app; only the .app is shipped.
    coll_dir = DIST / APP_NAME
    if coll_dir.is_dir() and coll_dir.resolve() != app_dir.resolve():
        shutil.rmtree(coll_dir)
    _assert_icon_present(app_dir)
    _assert_server_helper(app_dir)
    _assert_gui_info_plist(app_dir)
    _strip_packaging_metadata(app_dir)
    # Re-sign after plist edits (signature covers Info.plist).
    _resign_app_bundle(app_dir)
    # Critical-path scan + rename-away smoke (true portability proof).
    _assert_no_dev_paths(app_dir)
    _smoke_identity_and_imports(app_dir)
    _smoke_portability_rename(app_dir)

    size_mb = sum(
        p.stat().st_size for p in app_dir.rglob("*") if p.is_file()
    ) / (1024 * 1024)
    print(f"Built: {app_dir}  (~{size_mb:.0f} MB)")
    print(f"Icon:  {app_dir / 'Contents' / 'Resources' / (ICON_BASE_NAME + '.icns')}")
    print("Toolchain: PyInstaller windowed bootloader (in-process Python via dlopen)")
    print(f"Double-click it, or: open {app_dir!s}")
    return app_dir


if __name__ == "__main__":
    build()
