#!/usr/bin/env python3
"""Build a portable double-clickable macOS .app for M Maps.

Produces ``dist/M Maps.app`` that is self-contained for distribution:

- App code (``mmaps/``) is copied into ``Contents/Resources/app/``
- Dependencies from ``requirements.txt`` are installed into
  ``Contents/Resources/vendor/`` (``pip install -t``)
- The launcher resolves paths from its own location inside the bundle at
  runtime — nothing is hardcoded to the developer's checkout path

The interpreter is the standard macOS Command Line Tools Python
(``/Library/Developer/CommandLineTools/usr/bin/python3``, with
``/usr/bin/python3`` as fallback). That matches the README requirement
(Xcode CLT) and keeps the bundle free of a full Python.framework copy
while still running on any Apple Silicon Mac that meets Requirements.

The elevated server re-exec (``osascript`` admin dialog) reuses
``sys.executable`` and the same ``PYTHONPATH`` the launcher set, so it
also uses only paths inside the installed bundle.
"""
from __future__ import annotations

import os
import plistlib
import shutil
import stat
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
DIST = PROJECT_ROOT / "dist"
APP_NAME = "M Maps"
BUNDLE_ID = "local.mmaps.app"
ICON_ICNS = PROJECT_ROOT / "assets" / "icon" / "AppIcon.icns"
ICON_BASE_NAME = "AppIcon"
REQUIREMENTS = PROJECT_ROOT / "requirements.txt"
MMAPS_PKG = PROJECT_ROOT / "mmaps"

# Prefer CLT python (same as a typical project venv base on this platform).
CLT_PYTHON = Path("/Library/Developer/CommandLineTools/usr/bin/python3")
SYSTEM_PYTHON = Path("/usr/bin/python3")


def _launcher_script() -> str:
    # Paths are resolved at *runtime* from $0 — never baked to a build machine path.
    return r"""#!/bin/bash
# Auto-generated by build_app.py — do not edit by hand.
set -e
export PATH="/usr/bin:/bin:/usr/sbin:/sbin"

# Contents/MacOS → Contents → Resources (relative to this executable).
MACOS_DIR="$(cd "$(dirname "$0")" && pwd)"
CONTENTS_DIR="$(cd "$MACOS_DIR/.." && pwd)"
RES="$CONTENTS_DIR/Resources"
APP_DIR="$RES/app"
VENDOR_DIR="$RES/vendor"

if [ ! -d "$APP_DIR/mmaps" ]; then
  echo "M Maps is damaged or incomplete (missing Resources/app/mmaps)." >&2
  exit 1
fi
if [ ! -d "$VENDOR_DIR" ]; then
  echo "M Maps is damaged or incomplete (missing Resources/vendor)." >&2
  exit 1
fi

export PYTHONPATH="$APP_DIR:$VENDOR_DIR${PYTHONPATH:+:$PYTHONPATH}"
# .app root (parent of Contents) — used so the GUI can claim "M Maps" identity
# even though the interpreter binary is system python3.
export MMAPS_APP_BUNDLE="$(cd "$CONTENTS_DIR/.." && pwd)"
export MMAPS_APP_NAME="M Maps"

# Prefer Command Line Tools Python (wheels built for it); fall back to /usr/bin.
if [ -x "/Library/Developer/CommandLineTools/usr/bin/python3" ]; then
  PYTHON="/Library/Developer/CommandLineTools/usr/bin/python3"
elif [ -x "/usr/bin/python3" ]; then
  PYTHON="/usr/bin/python3"
else
  echo "Python 3 not found. Install Xcode Command Line Tools (xcode-select --install)." >&2
  exit 1
fi

# cd into the bundled app root so ``python -m`` does not pick up a random
# ``mmaps`` package from the user's shell cwd (sys.path[0] is the cwd).
cd "$APP_DIR"
# exec -a keeps argv[0] as "M Maps" (helps process lists). Identity for the
# menu bar / Dock is also fixed in mmaps.desktop via Cocoa before the window opens.
exec -a "M Maps" "$PYTHON" -m mmaps.desktop "$@"
"""


def _info_plist() -> dict:
    return {
        "CFBundleDevelopmentRegion": "en",
        "CFBundleDisplayName": APP_NAME,
        "CFBundleExecutable": APP_NAME,
        "CFBundleIconFile": ICON_BASE_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundleName": APP_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": "1.0.0",
        "CFBundleVersion": "1",
        "LSMinimumSystemVersion": "12.0",
        "NSHighResolutionCapable": True,
        "NSPrincipalClass": "NSApplication",
        "NSAppTransportSecurity": {
            "NSAllowsArbitraryLoadsInWebContent": True,
            "NSAllowsLocalNetworking": True,
        },
    }


def _copy_app_package(dest_app: Path) -> None:
    """Copy the mmaps package (with web + data assets) into Resources/app."""
    dest_pkg = dest_app / "mmaps"
    if dest_pkg.exists():
        shutil.rmtree(dest_pkg)
    shutil.copytree(
        MMAPS_PKG,
        dest_pkg,
        ignore=shutil.ignore_patterns("__pycache__", "*.py[cod]", ".DS_Store"),
    )


def _install_vendor(vendor_dir: Path) -> None:
    """Install runtime deps into Resources/vendor (self-contained site-packages)."""
    if vendor_dir.exists():
        shutil.rmtree(vendor_dir)
    vendor_dir.mkdir(parents=True, exist_ok=True)
    pip = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--disable-pip-version-check",
        "--no-compile",
        "-r",
        str(REQUIREMENTS),
        "-t",
        str(vendor_dir),
    ]
    print("Installing dependencies into bundle (this may take a minute)…")
    subprocess.check_call(pip)
    # Drop console-script wrappers (absolute shebangs from the build machine).
    scripts = vendor_dir / "bin"
    if scripts.is_dir():
        shutil.rmtree(scripts)
    # Pip metadata only; safe to keep. Prune a few bulky unused caches if any.
    for junk in vendor_dir.glob("**/*.pyc"):
        try:
            junk.unlink()
        except OSError:
            pass


def _assert_no_dev_paths(app_dir: Path) -> None:
    """Fail the build if a developer checkout path leaked into the bundle."""
    # Only scan text-ish launcher + small files; vendor has no absolute home paths
    # in normal wheels. Catch our own mistakes in the shell launcher.
    launcher = app_dir / "Contents" / "MacOS" / APP_NAME
    text = launcher.read_text(encoding="utf-8")
    for needle in ("/Users/", "/home/", "Developer/m-maps", "venv/bin"):
        if needle in text:
            raise SystemExit(
                f"Portability check failed: launcher contains {needle!r}.\n"
                f"  {launcher}"
            )


def build() -> Path:
    if sys.platform != "darwin":
        raise SystemExit("Building the .app is macOS-only.")
    if not MMAPS_PKG.is_dir():
        raise SystemExit(f"Missing package: {MMAPS_PKG}")
    if not REQUIREMENTS.is_file():
        raise SystemExit(f"Missing {REQUIREMENTS}")
    if not ICON_ICNS.is_file():
        raise SystemExit(
            f"Missing app icon {ICON_ICNS}.\n"
            "Run: venv/bin/python3 scripts/make_app_icon.py"
        )
    if not (CLT_PYTHON.is_file() or SYSTEM_PYTHON.is_file()):
        raise SystemExit(
            "No system Python found. Install Xcode Command Line Tools first."
        )

    app_dir = DIST / f"{APP_NAME}.app"
    contents = app_dir / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"
    app_code = resources / "app"
    vendor = resources / "vendor"

    if app_dir.exists():
        shutil.rmtree(app_dir)
    macos.mkdir(parents=True, exist_ok=True)
    resources.mkdir(parents=True, exist_ok=True)

    executable = macos / APP_NAME
    executable.write_text(_launcher_script(), encoding="utf-8")
    executable.chmod(
        executable.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
    )

    with (contents / "Info.plist").open("wb") as fh:
        plistlib.dump(_info_plist(), fh)
    (contents / "PkgInfo").write_text("APPL????", encoding="ascii")
    shutil.copy2(ICON_ICNS, resources / f"{ICON_BASE_NAME}.icns")

    print("Copying mmaps package into Resources/app …")
    _copy_app_package(app_code)
    _install_vendor(vendor)
    _assert_no_dev_paths(app_dir)

    # Quick import smoke-test using the same interpreter the launcher will use.
    python = str(CLT_PYTHON if CLT_PYTHON.is_file() else SYSTEM_PYTHON)
    env = os.environ.copy()
    env["PYTHONPATH"] = f"{app_code}{os.pathsep}{vendor}"
    subprocess.check_call(
        [python, "-c", "import mmaps.desktop, mmaps.server, webview, pymobiledevice3"],
        env=env,
    )

    size_mb = sum(p.stat().st_size for p in app_dir.rglob("*") if p.is_file()) / (1024 * 1024)
    print(f"Built: {app_dir}  (~{size_mb:.0f} MB)")
    print(f"Icon:  {resources / (ICON_BASE_NAME + '.icns')}")
    print("Bundle is self-contained (app + vendor inside Resources; no checkout path).")
    print(f"Double-click it, or: open {app_dir!s}")
    return app_dir


if __name__ == "__main__":
    build()
