# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_app.py — do not edit by hand.
# PyInstaller onedir + windowed → dist/M Maps.app with in-process bootloader.

block_cipher = None

from pathlib import Path
from PyInstaller.utils.hooks import collect_all, collect_submodules

_ROOT = Path(r"/Users/mj/Developer/m-maps")
_ICON = r"/Users/mj/Developer/m-maps/assets/icon/AppIcon.icns"

_datas = [
    (str(_ROOT / "mmaps" / "web"), "mmaps/web"),
    (str(_ROOT / "mmaps" / "data"), "mmaps/data"),
]
_binaries = []
_hidden = [
    "mmaps",
    "mmaps.desktop",
    "mmaps.server",
    "mmaps.session",
    "mmaps.device",
    "mmaps.location",
    "mmaps.route",
    "mmaps.flight",
    "mmaps.airports",
    "mmaps.trip",
    "mmaps.errors",
    "mmaps.cli",
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "webview",
    "webview.platforms.cocoa",
]

for _pkg in ("pymobiledevice3", "webview", "fastapi", "starlette", "anyio"):
    try:
        d, b, h = collect_all(_pkg)
        _datas += d
        _binaries += b
        _hidden += h
    except Exception:
        pass

try:
    _hidden += collect_submodules("uvicorn")
except Exception:
    pass

a = Analysis(
    [str(_ROOT / "packaging" / "desktop_entry.py")],
    pathex=[str(_ROOT)],
    binaries=_binaries,
    datas=_datas,
    hiddenimports=list(dict.fromkeys(_hidden)),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[str(_ROOT / "packaging" / "rthook_stub_ipython.py")],
    # IPython is only used by pymobiledevice3 for an optional CLI shell; the
    # real stack breaks in a windowed frozen app. Stubbed via runtime hook.
    excludes=[
        "IPython",
        "jedi",
        "prompt_toolkit",
        "matplotlib",
        "notebook",
        "jupyter",
        "jupyter_client",
        "jupyter_core",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# GUI bootloader (windowed runw) — Dock / Cmd+Tab identity for the user process.
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="M Maps",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=True,
    target_arch=None,
    codesign_identity="-",
    entitlements_file=None,
    icon=_ICON,
)

# Headless elevated tunnel/server helper (console run bootloader).
# Must NOT re-use the windowed "M Maps" binary: a second runw instance of the
# same .app fights the GUI process (Dock/AppKit contention → beachball / ANR).
exe_server = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="mmaps-server",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity="-",
    entitlements_file=None,
)

# Order matters: BUNDLE takes console= from the last EXE. Keep the GUI
# (console=False) last so PyInstaller does not mark the whole .app as a
# background-only agent (that was making the Dock icon ignore system tint).
coll = COLLECT(
    exe_server,
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="M Maps",
)

app = BUNDLE(
    coll,
    name="M Maps.app",
    icon=_ICON,
    bundle_identifier="local.mmaps.app",
    version="1.0.3",
    info_plist={
        "CFBundleDevelopmentRegion": "en",
        "CFBundleDisplayName": "M Maps",
        "CFBundleExecutable": "M Maps",
        "CFBundleIconFile": "AppIcon",
        # Lets Launch Services resolve the named icon asset (matches Safari/etc.).
        "CFBundleIconName": "AppIcon",
        "CFBundleIdentifier": "local.mmaps.app",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundleName": "M Maps",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": "1.0.3",
        "CFBundleVersion": "1.0.3",
        "LSMinimumSystemVersion": "12.0",
        # CRITICAL: console helper must not force background-only on the GUI app.
        # LSBackgroundOnly=true → Dock skips normal app-icon styling/tint.
        "LSBackgroundOnly": False,
        "LSUIElement": False,
        "NSHighResolutionCapable": True,
        "NSPrincipalClass": "NSApplication",
        "NSAppTransportSecurity": {
            "NSAllowsArbitraryLoadsInWebContent": True,
            "NSAllowsLocalNetworking": True,
        },
    },
)
